files:
  - source: /lang/en.json
    translation: /lang/%two_letters_code%.json
    type: json

  - source: /lang/action-en.json
    translation: /lang/action-%two_letters_code%.json
    type: json

  - source: /lang/re-en.json
    translation: /lang/re-%two_letters_code%.json
    type: json

  - source: /babele/compendium/en/*.json
    translation: /babele/compendium/%two_letters_code%/%original_file_name%
    type: json